# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../add_to_app_flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'ios-project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  flutter_application_path = '../add_to_app_flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

  # Pods for ios-project

end
