flutter_application_path = '../add_to_app_flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'ios-project' do
    install_all_flutter_pods(flutter_application_path)
end